### ISSUE TITLE
Video Orientation Incorrect

### ISSUE THREAD

**Issue by ttseng** [rheaton/carrierwave-video#21]
I have a video that is 1080 x 1920.  When it gets uploaded via carrierwave-video, the video appears to be rotated 90 degrees counter-clockwise.  How can I ensure that the video is not rotated?  What types of methods can I use to detect the video's dimensions when the user uploads the file?

This is only an issue when uploading portrait videos.

**Comment by damujay** [comment]
I am facing the issue with a portrait video.The thumbnail is rotating right. I am using the above code.Can you suggest me on that.

when i am removing **custom** attribute working fine but image is a blur and stretch more.

please tell me what type of custom attribut need to use.
