### ISSUE TITLE
Compatibility with streamio-ffmpeg 2.1.0

### ISSUE THREAD

**Issue by lilfaf** [rheaton/carrierwave-video#44]
Hi,

After updating streamio-ffmpeg to the latest version 2.1.0, I get the following error.

`
CarrierWave::ProcessingError:
Failed to transcode with FFmpeg. Check ffmpeg install and verify video is not corrupt or cut short. Original error: no implicit conversion of String into Array
`

**Comment by edwardvalentini** [comment]
+1

**Comment by thomasczer** [comment]
Same thing with 3.0.0

**Comment by strivemag** [comment]
is there any solution?

**Comment by phylor** [comment]
https://github.com/rheaton/carrierwave-video/pull/45 fixes this issue.
