### ISSUE TITLE
set uploaded video length limit

### ISSUE THREAD

**Issue by dcalixto** [rheaton/carrierwave-video#51]
After setup the carrier-wave video, i noticed that after upload the video the gem has a after_transcode: :set_success callback. that seems possible to configure.

I would like to know if by carrierwave is possible to set the video lenght after or before the transcoding by carrierwave.

Because in the docs seems that don't have mention to that.

**Comment by RailsCod3rFuture** [comment]
Would be a great feature to have. The cost of uploading video is so high, that its necessary.
